name: Test and Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -v ./...

    - name: Run coverage
      run: go test -race -coverprofile=coverage.out -covermode=atomic
    
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
